{% set name = "pyclustering" %}
{% set version = "0.10.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a98fd299fcc1e21b7b7c963275162dd7194aa3d921aa66d313775597cf833d1

build:
  number: 4
  ignore_run_exports:
    - libcxx  # [osx]
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<35]
  missing_dso_whitelist:
    - '*'

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - matplotlib-base
    - numpy
    - pillow
    - scipy

test:
  imports:
    - pyclustering
    - pyclustering.cluster
    - pyclustering.cluster.examples
    - pyclustering.cluster.tests
    - pyclustering.cluster.tests.integration
    - pyclustering.cluster.tests.unit
    - pyclustering.container
    - pyclustering.container.examples
    - pyclustering.container.tests
    - pyclustering.container.tests.unit
    - pyclustering.core
    - pyclustering.core.tests
    - pyclustering.gcolor
    - pyclustering.gcolor.examples
    - pyclustering.gcolor.tests
    - pyclustering.nnet
    - pyclustering.nnet.examples
    - pyclustering.nnet.tests
    - pyclustering.nnet.tests.integration
    - pyclustering.nnet.tests.unit
    - pyclustering.samples
    - pyclustering.tests
    - pyclustering.utils
    - pyclustering.utils.examples
    - pyclustering.utils.tests
    - pyclustering.utils.tests.integration
    - pyclustering.utils.tests.unit

about:
  home: https://github.com/annoviko/pyclustering
  license: BSD-3-Clause
  license_file: LICENSE
  summary: pyclustring is a python data mining library
  doc_url: https://pyclustering.github.io/docs/0.10.1/html/index.html
  dev_url: https://github.com/annoviko/pyclustering

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - benhuff
    - agcopenhaver
